/**
 * Slim answer-page index (slug / question / category / meta / services) plus
 * the service- and area-scoped helpers. Global chrome, the homepage and
 * cross-link modules import THIS module; the full answer content
 * (answer-pages.ts) is imported only by /answers/$slug.
 *
 * GENERATED by scripts/gen-data-summaries.mjs — do not edit by hand. Run
 * `bun scripts/gen-data-summaries.mjs --write` after changing answer-pages.ts;
 * scripts/test-data-sync.mjs fails when this drifts.
 */
export type AnswerCategory =
  | "cost"
  | "time"
  | "process"
  | "trust"
  | "coverage"
  | "emergency"
  | "comparison"
  | "care"
  | "car";

export const ANSWER_CATEGORIES: { id: AnswerCategory; label: string }[] = [
  { id: "cost", label: "Cost & pricing" },
  { id: "time", label: "Time & booking" },
  { id: "process", label: "How it works" },
  { id: "trust", label: "Trust & guarantees" },
  { id: "coverage", label: "Coverage & areas" },
  { id: "emergency", label: "Emergency & breakdown" },
  { id: "comparison", label: "Comparisons" },
  { id: "care", label: "Care & vehicle-specific" },
  { id: "car", label: "Car service" },
];

export interface AnswerPageSummary {
  slug: string;
  /** The question, used verbatim as the page H1. */
  question: string;
  category: AnswerCategory;
  /** 120–155 char meta description; also used for related-answer scoring. */
  meta?: string;
  /** Service slugs this answer links to. */
  services: string[];
}

export const ANSWER_PAGE_SUMMARY: AnswerPageSummary[] = [
  { slug: "car-service-interval", question: "How often should I get my car serviced?", category: "car", meta: "Service your car on the owner's-manual interval — months and kilometres, whichever comes first — and lean towards the earlier end in Bangalore traffic.", services: ["car-periodic-service","cars"] },
  { slug: "ev-what-can-be-serviced", question: "What can be serviced on an electric two-wheeler at home?", category: "care", meta: "EV doorstep service covers brakes, tyres, suspension and running gear with inspection checks — battery packs, BMS and motor faults stay with the manufacturer.", services: ["scooter-service","bike-service"] },
  { slug: "ktm-duke-200-service-cost", question: "How much does a KTM Duke 200 service cost in Bangalore?", category: "cost", meta: "KTM Duke 200 doorstep service in Bangalore: ₹999 General Service, ₹1,449 with engine oil — written quote before work starts, parts at MRP after approval.", services: ["bike-service","motorcycle-service"] },
  { slug: "brake-warning-signs-bike", question: "What are the warning signs my bike brakes need service?", category: "care", meta: "Squeal, longer lever travel, longer stopping distances or pulsation mean your bike brakes need inspection — grinding means pads are done, don't ride it out.", services: ["brake-service","bike-service"] },
  { slug: "bike-service-cost-bangalore", question: "How much does bike service cost in Bangalore?", category: "cost", meta: "Bike service in Bangalore starts at ₹799 General Service up to 199cc, scaling by engine size — the full price list, and what changes the final bill.", services: ["bike-service","doorstep-bike-service"] },
  { slug: "car-service-cost-bangalore", question: "How much does car service cost in Bangalore?", category: "cost", meta: "Car service pricing in Bangalore depends on model, oil grade and parts condition — what drives the quote, confirmed in writing before work starts.", services: ["car-periodic-service","car-ac-service","car-battery-service","car-brake-service"] },
  { slug: "bike-repair-cost", question: "How much does bike repair cost in Bangalore?", category: "cost", meta: "Bike repair in Bangalore starts with free diagnosis; Running Repair is ₹450 with parts quoted at MRP and approved before anything is fitted.", services: ["bike-repair","doorstep-bike-repair"] },
  { slug: "scooter-service-cost", question: "How much does scooter service cost in Bangalore?", category: "cost", meta: "Scooter service in Bangalore is ₹799 General Service up to 199cc, or ₹1,249 with engine oil — the same package prices as bikes of the same size.", services: ["scooter-service"] },
  { slug: "battery-jump-start-cost", question: "How much does a bike battery jump start cost?", category: "cost", meta: "A bike jump start in Bangalore costs ₹399 and includes a battery and charging-system check, so the real cause is found before it strands you again.", services: ["battery-service","doorstep-bike-repair"] },
  { slug: "ev-service-cost", question: "How much does electric scooter or bike service cost?", category: "cost", meta: "Electric scooter service at Ride N Care is flat-priced: ₹999 EV General Service, ₹450 Running Repair, ₹399 Jump Start — battery faults stay with the maker.", services: ["scooter-service"] },
  { slug: "how-long-bike-service", question: "How long does a bike service take at home?", category: "time", meta: "A bike General Service takes 60–90 minutes at your home, and 75–120 minutes with engine oil replacement — the arrival window is confirmed when you book.", services: ["bike-service","doorstep-bike-service"] },
  { slug: "how-long-car-service", question: "How long does a car service take at home?", category: "time", meta: "Car job durations are not pre-quoted; your arrival window is confirmed at booking and the visit ends when the checklist is complete and inspected.", services: ["car-periodic-service"] },
  { slug: "how-to-book", question: "How do I book a doorstep bike service in Bangalore?", category: "time", meta: "Book doorstep bike service in Bangalore by phone or WhatsApp with your model, address and slot — a written quote arrives before the mechanic is dispatched.", services: ["bike-service","doorstep-bike-service"] },
  { slug: "do-you-work-weekends", question: "Do you provide bike service on weekends and holidays?", category: "time", meta: "Doorstep bike service in Bangalore runs 7:00 AM to 11:30 PM, every day including weekends and holidays — book by call or WhatsApp and the arrival window is confirmed when you book.", services: ["emergency-bike-repair","doorstep-bike-service"] },
  { slug: "what-to-prepare", question: "What should I prepare before a doorstep service?", category: "time", meta: "For a doorstep service you only need parking space, gate access and ideally a plug point — the mechanic brings tools, oil, filters, spares and a drip tray.", services: ["doorstep-bike-service","bike-service"] },
  { slug: "what-included-bike-service", question: "What is included in a bike general service?", category: "process", meta: "A bike General Service covers filters, brakes, chain, clutch, cables, battery, electricals and a dry wash — with every item ticked off in front of you.", services: ["bike-service","periodic-bike-service"] },
  { slug: "written-quote", question: "Do you give a quote before starting work?", category: "process", meta: "Every job starts with a written quote covering parts, labour and the slot — nothing is touched until you approve it, and extra work is quoted separately.", services: ["doorstep-bike-service","bike-service"] },
  { slug: "payment-options", question: "How do I pay for the service?", category: "process", meta: "Pay by UPI, card or cash after a test ride — the digital invoice listing parts and labour separately reaches your WhatsApp as soon as the job closes.", services: ["bike-service"] },
  { slug: "are-mechanics-verified", question: "Are Ride N Care mechanics verified?", category: "trust", meta: "Ride N Care mechanics are background-verified, work in the open where you can watch, and hand over old parts — transparency is the practical safeguard.", services: ["doorstep-bike-service"] },
  { slug: "is-doorstep-service-safe", question: "Is doorstep bike service safe?", category: "trust", meta: "Doorstep service is safe because it happens in front of you — written quote first, parts shown, digital invoice, 45-day service warranty.", services: ["doorstep-bike-service"] },
  { slug: "guarantee", question: "Is there a guarantee on the work?", category: "trust", meta: "Every job carries a 45-day service warranty: if an issue related to our work appears within 45 days, we inspect and correct it in accordance with the warranty.", services: ["bike-service","bike-repair"] },
  { slug: "genuine-parts", question: "Do you use genuine spare parts?", category: "trust", meta: "Only OEM or OEM-grade parts are fitted — oil and spares are shown to you before fitting, and the digital invoice lists every part with part numbers.", services: ["bike-service","bike-repair"] },
  { slug: "which-oil", question: "Which engine oil do you use for my bike?", category: "trust", meta: "The oil grade your owner's manual specifies is used — wet-clutch motorcycles are grade-sensitive, and the exact grade is recorded on your invoice.", services: ["motorcycle-service","bike-service"] },
  { slug: "areas-covered", question: "Which areas of Bangalore do you cover?", category: "coverage", meta: "Ride N Care serves 40 confirmed localities across Bangalore — share your pincode on WhatsApp and get a straight yes or no on coverage.", services: ["doorstep-bike-service"] },
  { slug: "need-to-be-home", question: "Do I need to be home during the service?", category: "coverage", meta: "Be there at the start to approve the quote and at the end to inspect the work; the middle of the job needs no supervision from you.", services: ["doorstep-bike-service"] },
  { slug: "apartment-basement", question: "Can you service my bike in an apartment basement?", category: "coverage", meta: "Apartment basements are routine doorstep work — a drip tray, two bays of room and gate permission are all that is needed for a clean, contained job.", services: ["doorstep-bike-service","scooter-service"] },
  { slug: "bike-wont-start", question: "My bike will not start — what should I do?", category: "emergency", meta: "Bike not starting? Check fuel, the kill switch and side-stand first — then call 080 6940 9289 and a mechanic comes with a jump pack and spares.", services: ["emergency-bike-repair","bike-repair"] },
  { slug: "bike-stalled-in-water", question: "My bike stalled in a waterlogged street — what now?", category: "emergency", meta: "If your bike stalled in a waterlogged street, do not keep cranking — water in the airbox must be cleared first. Call 080 6940 9289 with your location.", services: ["emergency-bike-repair","bike-breakdown-assistance"] },
  { slug: "emergency-cost", question: "What does an emergency bike repair callout cost?", category: "emergency", meta: "Emergency bike repair callouts are quoted on the phone before dispatch; Running Repair is ₹450 and parts are billed at MRP only after your approval.", services: ["emergency-bike-repair"] },
  { slug: "recovery-after-breakdown", question: "What happens if my bike cannot be repaired on the spot?", category: "emergency", meta: "If a bike cannot be made rideable safely it is recovered to the nearest workshop once you approve — the repair estimate is shared before work begins.", services: ["bike-breakdown-assistance","emergency-bike-repair"] },
  { slug: "doorstep-vs-garage-bike", question: "Is doorstep bike service better than a garage?", category: "comparison", meta: "Doorstep bike service matches a garage on parts and tools while saving the trip; rebuilds and paint stay at the workshop. Honest limits, compared.", services: ["doorstep-bike-service","bike-service"] },
  { slug: "doorstep-vs-garage-car", question: "Is doorstep car service better than a service centre?", category: "comparison", meta: "Doorstep car service covers periodic, AC, battery and brake work with OEM-grade parts; overhauls, alignment and bodywork stay at the workshop.", services: ["car-periodic-service","car-ac-service"] },
  { slug: "periodic-vs-breakdown", question: "What is the difference between periodic service and breakdown service?", category: "comparison", meta: "Periodic service is scheduled maintenance before anything fails; breakdown service fixes the fault that stopped the bike. The cost logic differs too.", services: ["periodic-bike-service","emergency-bike-repair"] },
  { slug: "bike-vs-scooter-maintenance", question: "How does bike maintenance differ from scooter maintenance?", category: "comparison", meta: "Motorcycles need chain and clutch care; scooters need CVT belt, rollers and final-drive gear oil — the maintenance lists differ more than owners expect.", services: ["scooter-service","motorcycle-service"] },
  { slug: "monsoon-bike-care", question: "How should I care for my bike in monsoon?", category: "care", meta: "Monsoon bike care in Bangalore means chain lube after wet rides, tyre and brake checks, and an airbox inspection after any deep wading.", services: ["bike-service","brake-service"] },
  { slug: "service-interval", question: "How often should I service my bike in Bangalore?", category: "care", meta: "Service a bike in Bangalore roughly every 2,500–3,500 km or three months — traffic and dust wear oil faster than the manual assumes. Check your manual.", services: ["periodic-bike-service","bike-service"] },
  { slug: "roadside-or-garage", question: "Can every repair be done at my doorstep?", category: "care", meta: "Most bike repairs happen at your doorstep; engine strip-downs, wheel truing and paint need workshop equipment — the assessment on site decides honestly.", services: ["doorstep-bike-repair","bike-repair"] },
  { slug: "ev-service-different", question: "How is electric two-wheeler service different?", category: "care", meta: "EV service skips oil and plugs — the checklist becomes brakes, tyres, bearings, connectors and charging, with battery faults left to the maker.", services: ["scooter-service"] },
  { slug: "warranty-service", question: "Will doorstep service void my bike's warranty?", category: "care", meta: "During the free-service period use the authorised centre for those visits; after that, doorstep periodic service follows the same manufacturer schedule.", services: ["periodic-bike-service","car-periodic-service"] },
  { slug: "car-ac-not-cooling", question: "Why is my car AC not cooling?", category: "car", meta: "Weak car AC usually traces to low refrigerant, a clogged cabin filter, a dirty coil or a compressor that is not engaging — each is measured before a fix.", services: ["car-ac-service"] },
  { slug: "car-ac-service-includes", question: "What does a car AC service include?", category: "car", meta: "A car AC service includes a gas check and top-up, coil and condenser cleaning, cabin filter inspection and a vent-temperature test at your doorstep.", services: ["car-ac-service"] },
  { slug: "car-ac-gas-refill", question: "How does a car AC gas refill work?", category: "car", meta: "A car AC gas refill starts with a leak check — refilling a leaking system wastes money — then the correct refrigerant goes in by specified weight.", services: ["car-ac-service"] },
  { slug: "what-included-car-service", question: "What does a periodic car service include?", category: "car", meta: "A car periodic service at home covers oil and filters, brakes, fluids, battery, AC, lights, wipers, tyres and a multi-point inspection report.", services: ["car-periodic-service"] },
  { slug: "car-battery-warning-signs", question: "What are the warning signs of a failing car battery?", category: "car", meta: "Slow cranking, dim lights at idle and dash warnings are the classic signs of a failing car battery — Bangalore heat makes three years a common limit.", services: ["car-battery-service"] },
  { slug: "car-battery-replacement-when", question: "When does a car battery need replacement?", category: "car", meta: "A car battery needs replacement when testing shows it no longer holds charge or cranks reliably — commonly after three or four years in Bangalore heat.", services: ["car-battery-service"] },
  { slug: "car-brake-noise-causes", question: "Why do my car brakes squeal or grind?", category: "car", meta: "Brake squeal usually means worn or glazed pads; grinding means metal on metal — the car should be inspected before stopping power is compromised.", services: ["car-brake-service"] },
  { slug: "car-brake-pads-when", question: "When do car brake pads need changing?", category: "car", meta: "There is no single mileage for brake pads — check your owner's manual and watch for squeal, longer stopping distances or a pad-wear warning light.", services: ["car-brake-service"] },
  { slug: "monsoon-car-care", question: "What monsoon car care actually matters in Bangalore?", category: "car", meta: "Monsoon car care: tyres, wipers, brakes and drains checked before the rain, a fuller tank on flood-prone routes, and no driving through deep water.", services: ["car-periodic-service"] },
  { slug: "car-breakdown-rain", question: "My car broke down in the rain — what should I do?", category: "car", meta: "Car breaks down in the rain: safe spot, hazard lights on, stay belted if visibility is poor, and call with your location rather than attempting repairs.", services: ["car-breakdown-assistance"] },
  { slug: "doorstep-vs-workshop-car", question: "Doorstep or workshop — which suits my car job?", category: "car", meta: "Periodic, AC, battery and brake work are doorstep jobs; hoist, alignment and bodywork are workshop work — the honest dividing line is equipment.", services: ["car-periodic-service","cars"] },
  { slug: "can-every-car-job-home", question: "Can every car job be done at home?", category: "car", meta: "No — periodic, AC, battery and brake jobs happen at home; overhauls, bodywork and alignment need the workshop. The answer comes before you book.", services: ["cars","car-periodic-service"] },
  { slug: "how-to-prepare-car-doorstep", question: "How do I prepare my car for a doorstep service?", category: "car", meta: "One parking bay with working room, gate access sorted and the car unlocked — the mechanic brings tools, oil, filters and consumables to your door.", services: ["car-periodic-service","cars"] },
];

export const getAnswerSummary = (slug: string) => ANSWER_PAGE_SUMMARY.find((p) => p.slug === slug);

/** Answer pages that link to a given service slug (for "Related answers" on service pages). */
export function answersForService(slug: string, limit = 4): AnswerPageSummary[] {
  return ANSWER_PAGE_SUMMARY.filter((p) => p.services.includes(slug)).slice(0, limit);
}

/**
 * Answers relevant to a locality: vehicle + booking questions apply everywhere;
 * coverage answers mention the area network. Drives the "Related answers"
 * module on /areas/* pages so every area page links into the answers cluster.
 */
export function answersForArea(areaName: string, limit = 4): AnswerPageSummary[] {
  const byCategory = ["coverage", "cost", "time", "trust", "care"]
    .map((cat) => ANSWER_PAGE_SUMMARY.filter((p) => p.category === cat))
    .flat();
  const seen = new Set<string>();
  const picked: AnswerPageSummary[] = [];
  for (const p of byCategory) {
    if (picked.length >= limit) break;
    if (seen.has(p.slug)) continue;
    seen.add(p.slug);
    picked.push(p);
  }
  // One locality-aware entry keeps the block from being purely generic.
  const coverage = ANSWER_PAGE_SUMMARY.find((p) => p.slug === "areas-covered");
  if (coverage && !seen.has(coverage.slug)) picked.unshift(coverage);
  return picked.slice(0, limit);
}
