/**
 * Slim guide index (slug / titles / summary / read time) for the homepage,
 * /guides and cross-link modules. The full guide bodies (guides.ts) load only
 * on /guides/$slug.
 *
 * GENERATED by scripts/gen-data-summaries.mjs — do not edit by hand. Run
 * `bun scripts/gen-data-summaries.mjs --write` after changing guides.ts;
 * scripts/test-data-sync.mjs fails when this drifts.
 */
export interface GuideSummary {
  slug: string;
  title: string;
  h1: string;
  description: string;
  /** Answer-first summary paragraph. */
  summary: string;
  published: string;
  readMinutes: number;
}

export const GUIDE_SUMMARY: GuideSummary[] = [
  { slug: "bike-service-guide-bangalore", title: "Bike Service Guide for Bangalore (2026) | Ride N Care", h1: "Bike Service Guide for Bangalore", description: "Bike service guide for Bangalore riders: service intervals for city traffic, what a service includes, realistic costs and how doorstep service works.", summary: "In Bangalore's stop-start traffic, most commuter bikes need a service every 2,500–3,500 km or every three months, whichever comes first. A correct service covers engine oil, both filters, brakes, chain, clutch and throttle play, battery and tyres, and ends with a written inspection report.", published: "2026-02-14", readMinutes: 8 },
  { slug: "complete-bike-maintenance-guide", title: "Complete Bike Maintenance Guide | Ride N Care Bangalore", h1: "Complete Bike Maintenance Guide", description: "Two-wheeler maintenance guide: weekly, monthly and yearly checks for chain, brakes, tyres, battery, oil and electricals for Indian city riding.", summary: "Most two-wheeler breakdowns come from five neglected items: chain lubrication, tyre pressure, brake wear, battery terminals and engine oil. A five-minute weekly check and a monthly 15-minute check prevent the majority of roadside failures.", published: "2026-02-20", readMinutes: 9 },
  { slug: "common-bike-problems-and-solutions", title: "Common Bike Problems and Solutions | Ride N Care Bangalore", h1: "Common Bike Problems and Solutions", description: "Common two-wheeler problems by symptom: bike not starting, poor pickup, high fuel use, noises, smoke and electrical faults, with causes and fixes.", summary: "Most two-wheeler complaints trace back to a small number of causes: a weak battery, a clogged air filter, an out-of-adjustment chain or clutch, worn brake pads, or dirty fuel delivery. Matching the symptom to the likely cause first avoids paying for parts you did not need.", published: "2026-02-26", readMinutes: 10 },
  { slug: "when-to-service-your-bike", title: "When Should You Service Your Bike? | Ride N Care Bangalore", h1: "When Should You Service Your Bike?", description: "When your bike needs a service: kilometre and time intervals, warning symptoms, and how city riding and monsoon change the schedule.", summary: "Service your bike at whichever comes first — the kilometre interval or the time interval. For Bangalore city riding, that is roughly every 2,500–3,500 km or every three months. Certain symptoms override the schedule and mean a service now, regardless of the odometer.", published: "2026-03-04", readMinutes: 7 },
  { slug: "doorstep-bike-service-guide", title: "Doorstep Bike Service Guide | How It Works | Ride N Care", h1: "Doorstep Bike Service Guide", description: "How doorstep bike service works, what can and cannot be done at your address, how long it takes, what to prepare and how pricing and guarantees should work.", summary: "Doorstep bike service means a mechanic brings tools, consumables and spares to your address and completes the service where the bike is parked, usually in 60–90 minutes. Routine service and most mechanical and electrical repairs are suitable; engine rebuilds, wheel truing and painting are not.", published: "2026-03-10", readMinutes: 7 },
  { slug: "motorcycle-vs-scooter-maintenance", title: "Motorcycle vs Scooter Maintenance Guide | Ride N Care", h1: "Motorcycle vs Scooter Maintenance Guide", description: "How maintenance differs for motorcycles and automatic scooters: transmission, brakes, tyres, oil intervals and cost, so you service each correctly.", summary: "Motorcycles and automatic scooters wear differently. Motorcycles need chain, sprocket and clutch attention; scooters need CVT belt, roller and gear-oil attention instead. Scooters usually need shorter oil intervals and wear front brakes and small tyres faster.", published: "2026-03-16", readMinutes: 8 },
  { slug: "bike-breakdown-troubleshooting-guide", title: "Bike Breakdown Troubleshooting Guide | Ride N Care Bangalore", h1: "Bike Breakdown Troubleshooting Guide", description: "Roadside troubleshooting for bike breakdowns: what to check safely, which faults you can fix yourself, and when to call for emergency bike repair.", summary: "When a two-wheeler stops on the road, work through four checks in order — fuel, battery and switches, spark, and obvious mechanical damage. Most roadside failures are a flat battery, a fuse, a fuel-supply problem or a puncture, and only some are safe to fix yourself.", published: "2026-03-22", readMinutes: 8 },
];

export const getGuideSummary = (slug: string) => GUIDE_SUMMARY.find((g) => g.slug === slug);
