-- Batch 3 (Part 7): two blog posts from docs/seo/03-content-calendar.md
-- Week 9 item 4 (how often to service a car) and Week 12 item 3 (brake noise
-- causes). Seed mechanism matches migration 20260824173432 (INSERT into
-- public.blog_posts; RLS still blocks anon writes). Idempotent via slug
-- conflict guard. Content rules: no unverified claims (no response-time,
-- rating, count or availability claims); car services have no published
-- prices; written-quote + 7-day workmanship guarantee are confirmed facts.

INSERT INTO public.blog_posts (slug, title, excerpt, category, tags, author, read_mins, body, published, published_at) VALUES
('how-often-to-service-a-car',
 'How Often Should You Service Your Car? A Bangalore Owner''s Guide',
 'Months and kilometres, whichever comes first — what the manual interval really means in Bangalore traffic, and what a periodic service actually checks.',
 'Car Care', ARRAY['Car','Maintenance','Bangalore'], 'Ride N Care Team', 6,
 ARRAY[
  'Ask three car owners in Bangalore how often a car needs service and you will get three different answers. The honest one is unglamorous: the interval your owner''s manual specifies, counted in months and kilometres, whichever arrives first.',
  'Why two clocks? Because different parts of the car age in different ways. Engine oil degrades with heat cycles and moisture even when the car sits parked, which is why a rarely driven car still needs its time-based service. Brake fluid absorbs water from the air regardless of mileage. Rubber components — belts, wipers, hoses — age with time, not distance.',
  'Most modern cars fall somewhere between 6 and 12 months or 5,000 and 10,000 km for a periodic service, depending on the maker and the oil specified. Your manual is the authoritative source for your model — not a showroom brochure, not a friendly neighbourhood opinion.',
  'Then there is the Bangalore multiplier. Manufacturers write service schedules for average conditions. Dense stop-start traffic with constant braking, short trips that never fully warm the engine, summer heat that thins oil, and monsoon dust that clogs filters faster — these are precisely what the severe-conditions section of most manuals describes. If your car lives on ORR or commutes through the city daily, leaning towards the earlier end of the interval is not conservatism; it is reading the manual properly.',
  'What actually happens at a periodic service is worth understanding, because it explains why skipping one is a false economy. The checklist is inspection-led: engine oil and filter, air filter condition, brake pads and discs measured, coolant and other fluids topped or replaced, battery tested, tyres checked for tread and pressure, lights, wipers and suspension examined.',
  'The inspection is where the value hides. A periodic service finds the things you cannot feel from the driver''s seat — a brake pad one monsoon from the wear limit, a battery testing below spec, a tyre wearing unevenly from alignment. Found early, these are small line items. Found late, they become tow trucks and rebuild bills.',
  'A word on what a service is not: it is not an automatic parts spree. Pad thickness gets measured and shown to you before replacement is quoted. Filters are replaced when the inspection says so, not on a stopwatch. If a workshop replaces parts without showing you the worn ones, that is a question worth asking.',
  'Between services, three habits stretch the interval safely. Check tyre pressures monthly — under-inflation wears tyres fast in city heat. Note any change in brake feel or unusual noise the week it appears, rather than at the next service. And keep an eye on the dashboard: modern cars are honest about service-due reminders and fluid warnings.',
  'Warning lights deserve special mention. A service reminder is a calendar nudge. An oil-pressure light, a battery light or a temperature warning is the car reporting a live problem — those need attention that week, not at the next scheduled slot.',
  'For cars inside their free-service or warranty period, the authorised service centre remains the right place for scheduled visits — that is where the claim paperwork and free labour live. Once the car is out of that period, the calculation changes: an independent doorstep service with OEM-grade parts and a written quote covers the same checklist without surrendering a working day to a waiting lounge.',
  'However you service it, keep the record. A dated invoice with the odometer reading is what protects you at resale and keeps the next service correctly spaced. Digital invoices on WhatsApp count — what matters is that the date and reading are on them.',
  'If it has been more than a year, or the reminder has been quietly ignored since spring, the fix is one message. Ride N Care runs doorstep periodic car service across Bangalore — share your model on 080 6940 9289 or WhatsApp 82969 50339, and the full price is confirmed in writing before any work starts, backed by a 7-day workmanship guarantee.'
 ], true, '2026-09-27T09:00:00Z'),
('brake-noise-causes',
 'Why Do Brakes Squeal or Grind? The Causes, and When to Act',
 'Squeal, grind, or a lever that has grown soft — what each brake noise actually means, why the monsoon makes it worse, and when it becomes a stop-driving problem.',
 'Car Care', ARRAY['Brakes','Safety','Car','Bike'], 'Ride N Care Team', 6,
 ARRAY[
  'Brakes are the one system on your vehicle that announces their problems out loud. The trick is knowing which noises are routine and which mean stop driving. The rule of thumb, ahead of everything else in this article: grinding metal-on-metal is the loud end — the pads are done and every kilometre on them is scoring the discs.',
  'Start with the most common sound: squealing. Fresh surface rust on the discs after rain or a washed bike is the benign version — it fades after a few applications. Bangalore''s monsoon makes this a near-daily occurrence, and a squeal that disappears once things dry out is not a fault.',
  'Persistent squealing is different. Most pads carry a wear indicator — a small metal tab designed to contact the disc and squeal when the friction material is close to its limit. It is not a malfunction; it is the pad reporting in. Squeal that survives dry weather deserves an inspection within days, not months.',
  'Glazing is the quieter cousin. Hard braking from speed, or riding the brakes down long flyover descents, can heat pads past their comfortable range and leave the surface hardened and shiny. Glazed pads bite less and squeal more — the fix is replacement, and the habit fix is gentler use.',
  'Grinding is the one that reorders your week. When the friction material is exhausted, the pad''s steel backing contacts the disc directly. Stopping power is compromised, and each drive deepens the scoring — which converts a pad replacement into a disc replacement. If your brakes grind, minimise driving and book an inspection immediately.',
  'A soft or spongy lever or pedal is not a noise, but it belongs in the same conversation. Air or moisture in the brake fluid, a leaking seal, or a failing master cylinder show up as increased travel before anything audible. Reduced travel between services is worth checking the same week.',
  'Pulsation — a rhythmic push-back through the pedal or lever when braking — usually means a disc has warped from uneven heating, or rust has built up unevenly after the vehicle sat through a wet week. It is inspectable and measurable; the discs are either machinable or due for replacement.',
  'What does an honest brake inspection look like? Pad thickness is measured on both wheels and the numbers are shown to you, not described. Discs are measured for thickness and runout too, because a disc within spec does not need replacing — a workshop that quotes discs and pads together every time, without measurements, is quoting habit rather than condition.',
  'Two Bangalore-specific notes. First, dust: road dust and monsoon grit embed in pads and accelerate wear, so brake intervals here run shorter than the manual''s baseline suggests for many riders. Second, water: after any ride through a flooded street, brakes can grab or lose bite until the water clears — dry them gently with a few light applications rather than slamming to a stop mid-puddle.',
  'For two-wheelers, the same physics apply with one extra wrinkle: drum brakes, common on commuter bikes and scooter rears, hide their wear inside the hub. A drum brake that has lost free play adjustment at the cable can feel like worn shoes — the adjustment is a two-minute check that belongs in every service.',
  'Replacement parts themselves are not exotic: OEM or OEM-grade pads for your exact model, fitted with the discs measured and the fluid checked. Parts should be shown to you before fitting and itemised on the invoice, and the work should carry a written guarantee — at Ride N Care, a 7-day workmanship guarantee.',
  'If any of this sounds like your vehicle — a squeal that persists, a grind, a lever that has grown soft — brake pads and brake service are doorstep jobs. Describe the noise on 080 6940 9289 or WhatsApp 82969 50339, and the inspection, measurements and full written quote come to your parking spot before anything is replaced.'
 ], true, '2026-09-27T09:00:00Z')
ON CONFLICT (slug) DO NOTHING;
